name: Build and Deploy Azure Function App (Folder Deploy)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './build'
  AZURE_FUNCTIONAPP_NAME: openai-embedding-fn
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies into build folder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target="${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        shopt -s extglob
        cp -r !(build) ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        cp -r .python_packages ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} || true

    - name: Deploy to Azure Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

