name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies into build folder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target="./build"
        shopt -s extglob
        cp -r !(build) ./build
        cp -r .python_packages ./build || true

    - name: Zip build folder
      run: cd build && zip -r ../release.zip .

    - name: Deploy to Azure Function App (.zip method)
      uses: Azure/functions-action@v1
      with:
        app-name: openai-embedding-fn
        package: 'release.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: true
        respect-pom-xml: false
        respect-funcignore: false
        remote-build: false
