name: Build and Deploy Azure Function App (ZIP with Artifact)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies into build folder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target="./build"
        shopt -s extglob
        cp -r !(build) ./build
        cp -r .python_packages ./build || true

    - name: Create ZIP package
      run: cd build && zip -r ../release.zip .

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download ZIP artifact
      uses: actions/download-artifact@v4
      with:
        name: release-package

    - name: Deploy ZIP to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: openai-embedding-fn
        package: release.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Set WEBSITE_RUN_FROM_PACKAGE=1 (optional safety net)
      run: |
        echo "WEBSITE_RUN_FROM_PACKAGE=1" >> $GITHUB_ENV

