name: Build and Deploy Azure Function App (ZIP Method)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: openai-embedding-fn
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies into build folder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target="./build"
        shopt -s extglob
        cp -r !(build) ./build || true

    - name: Create ZIP package
      run: cd build && zip -r ../release.zip .

    - name: Deploy ZIP to Azure Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ./release.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
